In [317]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 선형회귀 관련 sklean 라이브러리 불러오기

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# 선형회귀 관련 statsmodels 라이브러리 불러오기

import statsmodels.api as sm

In [318]:
# 간단한 맛보기 예제

np.array([[0,1],[1,2],[2,2.5]])

array([[0. , 1. ],
       [1. , 2. ],
       [2. , 2.5]])

In [319]:
np.array([0,1.2,1.6])

array([0. , 1.2, 1.6])

In [320]:
# 데이터

X = np.array([[0,1],[1,2],[2,2.5]]) # 2차원 데이터
y = np.array([0,1.2,1.6])

In [321]:
# 선형회귀 객체 생성

reg = linear_model.LinearRegression()

In [322]:
# 훈련 데이터 >> fit 모델 적합 
reg.fit(X,y)

LinearRegression()

In [323]:
# train data로 예측

pred_train = reg.predict(X)
pred_train

array([4.4408921e-16, 1.2000000e+00, 1.6000000e+00])

In [324]:
# coefficient (기울기, beta1, beta2)
reg.coef_

array([-0.4,  1.6])

In [325]:
# advertising 데이터 불러오기기

path = '/content/drive/MyDrive/새싹sw-인공지능 서비스 개발자/CLASSROOM/CODE PDF/머신러닝/Advertising.csv'
ad = pd.read_csv(path, index_col=0)

In [326]:
# train data의 feature의 결과변수 분리
ad.columns

Index(['Unnamed: 0.1', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [327]:
train = ad[:20]
test = ad[-20:]

In [328]:
train_X = train[['TV', 'Radio', 'Newspaper']]

train_y = train[['Sales']]

In [329]:
# test data의 feature의 결과변수 분리
train_X = test[['TV', 'Radio', 'Newspaper']]

train_y = test[['Sales']]

In [330]:
# 선형회귀 객체 생성
regr = linear_model.LinearRegression()

In [331]:
# train data 이용 >> fit (모델 적합)

regr.fit(train_X[['TV', 'Radio', 'Newspaper']],train_y)

LinearRegression()

In [332]:
# train data 활용, 예측

train_y_pred = regr.predict(train_X[['TV', 'Radio', 'Newspaper']])

In [333]:
# test data 활용, 예측

test_y_pred = regr.predict(train_X[['TV', 'Radio', 'Newspaper']])

In [334]:
print("coefficiants: ",regr.coef_)

coefficiants:  [[0.03593836 0.20758821 0.04053024]]

-----

In [335]:
# 다항회귀(polynominal features) 예제

In [336]:
from sklearn.preprocessing import PolynomialFeatures

In [337]:
X = np.arange(6).reshape(3,-1)

In [338]:
# [1,a,b,a^2,ab,b^2] feature 생성
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [339]:
# interaction(상호작용) feature만 생성

poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

In [340]:
# auto data 활용, 다항회귀분석

path = '/content/drive/MyDrive/새싹sw-인공지능 서비스 개발자/CLASSROOM/CODE PDF/머신러닝/Auto.csv'
auto = pd.read_csv(path)

In [341]:
auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
392,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
393,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
394,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
395,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
396,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [342]:
# horsepower ? 값을 0 대체 

auto['horsepower'][:40]

0     130
1     165
2     150
3     150
4     140
5     198
6     220
7     215
8     225
9     190
10    170
11    160
12    150
13    225
14     95
15     95
16     97
17     85
18     88
19     46
20     87
21     90
22     95
23    113
24     90
25    215
26    200
27    210
28    193
29     88
30     90
31     95
32      ?
33    100
34    105
35    100
36     88
37    100
38    165
39    175
Name: horsepower, dtype: object

In [343]:
auto['horsepower']= auto['horsepower'].replace(to_replace='?',value=0)

In [344]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [345]:
# horsepower의 데이터타입 변경 (object >> numeric 숫자)

auto['horsepower'] = pd.to_numeric(auto['horsepower'])

In [346]:
auto['horsepower'].dtype

dtype('int64')

In [347]:
# auto data 다중선형회귀

# horsepower의 다양한 feature 생성

auto['horsepower_2'] = auto['horsepower']**2
auto['horsepower_3'] = auto['horsepower']**3
auto['horsepower_4'] = auto['horsepower']**4
auto['horsepower_5'] = auto['horsepower']**5
auto.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name,horsepower_2,horsepower_3,horsepower_4,horsepower_5
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,16900,2197000,285610000,37129300000
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,27225,4492125,741200625,122298103125
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,22500,3375000,506250000,75937500000
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,22500,3375000,506250000,75937500000
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,19600,2744000,384160000,53782400000

In [348]:
# train/test data 분리 

train= auto[:-40]
test = auto[-40:]

print(train)
print(test)

      mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70
1    15.0          8         350.0         165    3693          11.5    70
2    18.0          8         318.0         150    3436          11.0    70
3    16.0          8         304.0         150    3433          12.0    70
4    17.0          8         302.0         140    3449          10.5    70
..    ...        ...           ...         ...     ...           ...   ...
352  29.9          4          98.0          65    2380          20.7    81
353  33.0          4         105.0          74    2190          14.2    81
354  34.5          4         100.0           0    2320          15.8    81
355  33.7          4         107.0          75    2210          14.4    81
356  32.4          4         108.0          75    2350          16.8    81

     origin                       name  horsepower_2  horsepower_3  \
0         1  chevrolet chevelle malibu         16900       2197000
1         1          buick skylark 320         27225       4492125
2         1         plymouth satellite         22500       3375000
3         1              amc rebel sst         22500       3375000
4         1                ford torino         19600       2744000
..      ...                        ...           ...           ...
352       1             ford escort 2h          4225        274625
353       2           volkswagen jetta          5476        405224
354       2                renault 18i             0             0
355       3              honda prelude          5625        421875
356       3             toyota corolla          5625        421875

     horsepower_4  horsepower_5
0       285610000   37129300000
1       741200625  122298103125
2       506250000   75937500000
3       506250000   75937500000
4       384160000   53782400000
..            ...           ...
352      17850625    1160290625
353      29986576    2219006624
354             0             0
355      31640625    2373046875
356      31640625    2373046875

[357 rows x 13 columns]
      mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
357  32.9          4         119.0         100    2615          14.8    81
358  31.6          4         120.0          74    2635          18.3    81
359  28.1          4         141.0          80    3230          20.4    81
360  30.7          6         145.0          76    3160          19.6    81
361  25.4          6         168.0         116    2900          12.6    81
362  24.2          6         146.0         120    2930          13.8    81
363  22.4          6         231.0         110    3415          15.8    81
364  26.6          8         350.0         105    3725          19.0    81
365  20.2          6         200.0          88    3060          17.1    81
366  17.6          6         225.0          85    3465          16.6    81
367  28.0          4         112.0          88    2605          19.6    82
368  27.0          4         112.0          88    2640          18.6    82
369  34.0          4         112.0          88    2395          18.0    82
370  31.0          4         112.0          85    2575          16.2    82
371  29.0          4         135.0          84    2525          16.0    82
372  27.0          4         151.0          90    2735          18.0    82
373  24.0          4         140.0          92    2865          16.4    82
374  36.0          4         105.0          74    1980          15.3    82
375  37.0          4          91.0          68    2025          18.2    82
376  31.0          4          91.0          68    1970          17.6    82
377  38.0          4         105.0          63    2125          14.7    82
378  36.0          4          98.0          70    2125          17.3    82
379  36.0          4         120.0          88    2160          14.5    82
380  36.0          4         107.0          75    2205          14.5    82
381  34.0          4         108.0          70    2245          16.9    82
382  38.0          4          91.0          67    1965          15.0    82
383  32.0          4          91.0          67    1965          15.7    82
384  38.0          4          91.0          67    1995          16.2    82
385  25.0          6         181.0         110    2945          16.4    82
386  38.0          6         262.0          85    3015          17.0    82
387  26.0          4         156.0          92    2585          14.5    82
388  22.0          6         232.0         112    2835          14.7    82
389  32.0          4         144.0          96    2665          13.9    82
390  36.0          4         135.0          84    2370          13.0    82
391  27.0          4         151.0          90    2950          17.3    82
392  27.0          4         140.0          86    2790          15.6    82
393  44.0          4          97.0          52    2130          24.6    82
394  32.0          4         135.0          84    2295          11.6    82
395  28.0          4         120.0          79    2625          18.6    82
396  31.0          4         119.0          82    2720          19.4    82

     origin                               name  horsepower_2  horsepower_3  \
357       3                       datsun 200sx         10000       1000000
358       3                          mazda 626          5476        405224
359       2          peugeot 505s turbo diesel          6400        512000
360       2                       volvo diesel          5776        438976
361       3                    toyota cressida         13456       1560896
362       3                  datsun 810 maxima         14400       1728000
363       1                      buick century         12100       1331000
364       1              oldsmobile cutlass ls         11025       1157625
365       1                    ford granada gl          7744        681472
366       1             chrysler lebaron salon          7225        614125
367       1                 chevrolet cavalier          7744        681472
368       1           chevrolet cavalier wagon          7744        681472
369       1          chevrolet cavalier 2-door          7744        681472
370       1         pontiac j2000 se hatchback          7225        614125
371       1                     dodge aries se          7056        592704
372       1                    pontiac phoenix          8100        729000
373       1               ford fairmont futura          8464        778688
374       2                volkswagen rabbit l          5476        405224
375       3                 mazda glc custom l          4624        314432
376       3                   mazda glc custom          4624        314432
377       1             plymouth horizon miser          3969        250047
378       1                     mercury lynx l          4900        343000
379       3                   nissan stanza xe          7744        681472
380       3                       honda accord          5625        421875
381       3                     toyota corolla          4900        343000
382       3                        honda civic          4489        300763
383       3                 honda civic (auto)          4489        300763
384       3                      datsun 310 gx          4489        300763
385       1              buick century limited         12100       1331000
386       1  oldsmobile cutlass ciera (diesel)          7225        614125
387       1         chrysler lebaron medallion          8464        778688
388       1                     ford granada l         12544       1404928
389       3                   toyota celica gt          9216        884736
390       1                  dodge charger 2.2          7056        592704
391       1                   chevrolet camaro          8100        729000
392       1                    ford mustang gl          7396        636056
393       2                          vw pickup          2704        140608
394       1                      dodge rampage          7056        592704
395       1                        ford ranger          6241        493039
396       1                         chevy s-10          6724        551368

     horsepower_4  horsepower_5
357     100000000   10000000000
358      29986576    2219006624
359      40960000    3276800000
360      33362176    2535525376
361     181063936   21003416576
362     207360000   24883200000
363     146410000   16105100000
364     121550625   12762815625
365      59969536    5277319168
366      52200625    4437053125
367      59969536    5277319168
368      59969536    5277319168
369      59969536    5277319168
370      52200625    4437053125
371      49787136    4182119424
372      65610000    5904900000
373      71639296    6590815232
374      29986576    2219006624
375      21381376    1453933568
376      21381376    1453933568
377      15752961     992436543
378      24010000    1680700000
379      59969536    5277319168
380      31640625    2373046875
381      24010000    1680700000
382      20151121    1350125107
383      20151121    1350125107
384      20151121    1350125107
385     146410000   16105100000
386      52200625    4437053125
387      71639296    6590815232
388     157351936   17623416832
389      84934656    8153726976
390      49787136    4182119424
391      65610000    5904900000
392      54700816    4704270176
393       7311616     380204032
394      49787136    4182119424
395      38950081    3077056399
396      45212176    3707398432

In [349]:
# 훈련용 데이터의 feature와 response 분리

auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name', 'horsepower_2',
       'horsepower_3', 'horsepower_4', 'horsepower_5'],
      dtype='object')

In [350]:
train_x =\
train[['horsepower','horsepower_2','horsepower_3', 'horsepower_4', 'horsepower_5']]

In [351]:
train_y = train[['mpg']]

In [352]:
test_x = test[['horsepower','horsepower_2','horsepower_3', 'horsepower_4', 'horsepower_5']]

In [353]:
test_y = test[['mpg']]

In [354]:
# 선형회귀 객체 생성

regr = linear_model.LinearRegression()

In [355]:
# 훈련용 데이터 이용 >> 모델 적합하게 한다. 

regr.fit(train_x[['horsepower','horsepower_2','horsepower_3']],train_y)

LinearRegression()

In [356]:
# 훈련용 데이터 이용, 예측

train_y_pred = regr.predict(train_x[['horsepower','horsepower_2','horsepower_3']])

In [357]:
# 테스트 데이터 이용, 예측 

test_y_pred = regr.predict(test_x[['horsepower','horsepower_2','horsepower_3']])

In [358]:
# coeffients

print('cofficents', regr.coef_)

cofficents [[ 8.89265767e-02 -2.94597040e-03  9.81651841e-06]]

In [359]:
# train data MSE

print('Train_data mse: %.3f'%mean_squared_error(train_y,train_y_pred))

Train_data mse: 19.819

In [360]:
# train data MSE

print('Train_data mse: %.3f'%mean_squared_error(test_y,test_y_pred))

Train_data mse: 38.104

In [361]:
# train data r2_score

print('r2_score: %.3f'%r2_score(train_y,train_y_pred))

r2_score: 0.660

In [362]:
# test data r2_score

print('r2_score: %.3f'%r2_score(test_y,test_y_pred))

r2_score: -0.179